title : 叹为观止
tagline: 囊萤映雪，勤业博学
author :
  name : Victor Woo
  email : victorwoo@gmail.com
  github : victorwoo
  twitter : victorwoo
  feedburner : _feedname

navigation :
  - 存档.html
  - 标签.html
  - 分类.html
  - 页面.html
  - about.md
  
